Cherry pick of 6dfc8db40843075f263e22106df84547e4131c16 failed
stdout:

stderr:
error: could not apply 6dfc8db4084... [IMP] test_mail: add test for auto subscribe
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'